name: Fetch and Build Articles

on:
  schedule:
    - cron: '0 13 * * *'  # Runs daily at 6:00 AM PST (13:00 UTC)
  workflow_dispatch:      # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable default GITHUB_TOKEN to use custom token

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run fetch script
        env:
          PUBKEY: ${{ secrets.PUBKEY }}
        run: |
          python scripts/fetch_articles.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/andrewgstanton/blog-stantonweb-site.git

          git add docs/articles
          git commit -m "Auto-update articles" || echo "No changes to commit"
          git push origin main
